In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Aashi\Regression_ML_EndtoEnd\data\raw\untouched_raw_original.csv')
df

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,...,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,...,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Alpharetta
1,2012-04-30,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,...,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,Atlanta-Sandy Springs-Alpharetta
2,2012-05-31,125500.0,217450.0,63.913043,119.919216,24.0,40.0,63.0,60.0,144.5,...,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202681.309539,Atlanta-Sandy Springs-Alpharetta
3,2012-06-30,153000.0,189900.0,81.598080,105.617353,34.0,46.0,50.0,57.0,126.0,...,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202998.603897,Atlanta-Sandy Springs-Alpharetta
4,2012-07-31,165500.0,154000.0,81.598080,83.921175,39.0,49.0,42.0,50.0,80.0,...,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,203781.903446,Atlanta-Sandy Springs-Alpharetta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884087,2023-08-31,438000.0,450000.0,313.553299,322.866706,185.0,189.0,227.0,132.0,20.0,...,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,438238.668892,Tampa-St. Petersburg-Clearwater
884088,2023-09-30,449950.0,459900.0,314.024277,318.285714,192.0,189.0,243.0,170.0,18.0,...,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,440569.503271,Tampa-St. Petersburg-Clearwater
884089,2023-10-31,450000.0,449450.0,312.328767,314.374076,187.0,192.0,264.0,185.0,21.5,...,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,442965.899354,Tampa-St. Petersburg-Clearwater
884090,2023-11-30,470000.0,425000.0,312.328767,315.315315,175.0,182.0,279.0,213.0,21.0,...,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,444955.530200,Tampa-St. Petersburg-Clearwater
884091,2023-12-31,440000.0,399949.5,300.469484,317.925225,161.0,160.0,240.0,223.0,29.0,...,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,446862.962247,Tampa-St. Petersburg-Clearwater

In [3]:
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_rows', None)     # Show all rows

In [4]:
df.shape

(884092, 39)

In [5]:
df.head(2)

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Alpharetta
1,2012-04-30,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,0.946642,0.090909,0.034483,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,Atlanta-Sandy Springs-Alpharetta

In [ ]:
df['date'] = pd.to_datetime(df['date'])
print(df['date'].dt.year.value_counts().sort_index())
# we have splitted the data as per the year if we just splitted radnomly like 80-20 there will be a chance of data leakage

date
2012    62260
2013    74712
2014    74712
2015    74712
2016    74712
2017    74712
2018    74712
2019    74712
2020    74712
2021    74712
2022    74712
2023    74712
Name: count, dtype: int64

##### Avoid Leakage

- Your train set (2012–2019) is “clean” historical training.

- Your eval set (2020–2021) is “unseen” during training, but still used for validation and hyperparameter tuning.

- Your holdout set (2022–2023) is completely untouched until the very end.

In [11]:
# Sort by date (important to avoid shuffling issues)
df = df.sort_values("date")

In [12]:
# Define cutoff dates
cutoff_date_eval = "2020-01-01"   # validation starts
cutoff_date_holdout = "2022-01-01"  # holdout starts

In [15]:
# Train: before 2020
train_df=df[df['date']< cutoff_date_eval]
# Validation/Eval: 2020–2021
eval_df =df[(df["date"] >= cutoff_date_eval) & (df["date"]<cutoff_date_holdout)]
# Holdout: 2022–2023
holdout_df = df[df["date"] >= cutoff_date_holdout]

print("Train shape:", train_df.shape)
print("Eval shape:", eval_df.shape)
print("Holdout shape:", holdout_df.shape)

Train shape: (585244, 39)
Eval shape: (149424, 39)
Holdout shape: (149424, 39)

In [19]:
train_df.head(2)

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Alpharetta
640846,2012-03-31,97500.0,95400.0,78.828829,92.476852,6.0,5.0,7.0,15.0,92.5,0.930709,0.333333,0.000000,PGH,15473,2012,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,3769.0,49.8,24494.0,3747.0,1758.0,487.0,128600.0,1790.0,158.0,3733.0,3733.0,1507.0,121528.007331,Pittsburgh

In [20]:
eval_df.head(2)

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
80040,2020-01-31,344000.0,339450.0,172.171860,173.915289,56.0,53.0,48.0,18.0,18.5,0.992399,0.25,0.45283,BWI,20724,2020,4.0,0.0,1.0,0.0,27.0,17.0,22.0,2.0,6.0,17513.0,34.6,42817.0,17437.0,7205.0,1824.0,315500.0,10753.0,581.0,16947.0,16947.0,9548.0,336112.998501,Baltimore-Columbia-Towson
841444,2020-01-31,197500.0,160000.0,120.403912,87.859155,4.0,0.0,11.0,14.0,77.5,0.991463,0.00,0.00000,STL,62097,2020,1.0,0.0,0.0,0.0,3.0,3.0,3.0,0.0,0.0,2893.0,42.4,34320.0,2864.0,1106.0,815.0,165300.0,1626.0,74.0,2793.0,2793.0,1485.0,185819.512042,St. Louis

In [21]:
holdout_df.head(2)

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
442590,2022-01-31,300000.0,334900.0,168.656716,214.791901,77.0,52.0,67.0,36.0,17.0,1.028391,0.506494,0.615385,MSP,55056,2022,0.0,0.0,0.0,1.0,10.0,0.0,4.0,0.0,1.0,14084.0,40.4,38596.0,13963.0,5434.0,948.0,242400.0,7967.0,328.0,13751.0,13751.0,7001.0,324483.591297,Minneapolis-St. Paul-Bloomington
797590,2022-01-31,625169.5,599950.0,296.452898,295.774648,190.0,150.0,127.0,16.0,7.0,1.024232,0.594737,0.740000,SEA,98092,2022,1.0,0.0,0.0,0.0,87.0,16.0,25.0,0.0,4.0,50845.0,35.9,42339.0,50542.0,17689.0,1647.0,447500.0,26896.0,1131.0,49160.0,49160.0,22428.0,614921.882570,Seattle-Tacoma-Bellevue

In [27]:
# Save splits
train_df.to_csv(r"C:\Users\Aashi\Regression_ML_EndtoEnd\data\raw\train.csv", index=False)
eval_df.to_csv(r"C:\Users\Aashi\Regression_ML_EndtoEnd\data\raw\eval.csv", index=False)
holdout_df.to_csv(r"C:\Users\Aashi\Regression_ML_EndtoEnd\data\raw\holdout.csv", index=False)